services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    image: loseme-core:latest

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: loseme-client:latest
    ports:
      - "3000:3000"
    env_file:
      .env.client
    volumes:
      - ${LOSEME_HOST_ROOT}:/mnt/userdata
    depends_on:
      core:
        condition: service_completed_successfully
